### ISSUE TITLE
Feat: Feature to update the details of the service provider playground

### ISSUE THREAD

**Issue by Anandateertha** [BookMySport-com-Platform/Authentication-Service#3]
### Feature description: 

In this feature the implementation aims to give the service provider an option to update the details of his playground like,

1. Centre name
2. Address
3. Phone number
4. Start time
5. Stop time

**Comment by nkthis** [comment]
Why this feature PR request is added in auth service repo ?

**Comment by nkthis** [comment]
it should be placed in service provider repo.

**Comment by VortexProjects** [comment]
> Why this feature PR request is added in auth service repo ? should be placed in service provider repository

In this the service provider will be able to update the following details like,

1. Centre name
2. Address
3. Phone number
4. Start time
5. Stop time

Because these are defined in this service. The things like ,

1. Sport name
2. Price per hour of particular sport
3. Number of courts ( Availability of courts )

are updated in the Service Provider Place registration service.

Link to PR in Service Provider Place registration service which implements this: https://github.com/BookMySport-com-Platform/Service-Provider-Place-Registration/pull/5

**Comment by nkthis** [comment]
Okay Got your point

**Comment by VortexProjects** [comment]
> Okay Got your point

👍

**Comment by VortexProjects** [comment]
I am closing this issue as PR #4 implements the update feature.
